-- 20260806120000_cron_secret_store.sql
--
-- LEAD-FOLLOWUP-GHL-DELIVERY-AND-ADMIN-RESUME-CHECKOUT-EMAIL-002 — secret rotation.
--
-- WHY THIS TABLE EXISTS RATHER THAN JUST A NEW ENV VALUE
-- -----------------------------------------------------
-- `LEAD_FOLLOWUP_CRON_SECRET` had to be rotated because the old value was
-- exposed. It was exposed because it sat as a PLAINTEXT LITERAL inside
-- `cron.job.command`, where anyone reading the job definition — or any redaction
-- pattern that guessed the wrong syntax — surfaces it in full.
--
-- Putting a fresh literal back in the same place would rotate the value and
-- keep the defect. So the secret now lives in ONE place that is never selected
-- in ordinary queries, and the cron command references it by lookup instead of
-- carrying it:
--
--   headers := jsonb_build_object(..., 'x-cron-secret', private.cron_secret('lead_followup'))
--
-- Consequences that matter:
--   • `cron.job.command` contains no credential, so reading the schedule leaks
--     nothing.
--   • Rotation is a single in-database UPDATE. The value can be generated by
--     `gen_random_bytes` and never has to leave Postgres, be typed by a human,
--     pasted into a terminal, or appear in a transcript.
--   • The Edge Function reads the same row, so both sides rotate atomically —
--     there is no window where the caller and the verifier disagree.

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.cron_secrets (
  name        text primary key,
  secret      text not null,
  rotated_at  timestamptz not null default now()
);

alter table private.cron_secrets enable row level security;
-- No policies, deliberately: RLS with zero policies denies everything except
-- the service role, which bypasses RLS. Nothing else can read this table.
revoke all on table private.cron_secrets from public, anon, authenticated;

comment on table private.cron_secrets is
  'Shared secrets for pg_cron -> Edge Function calls. Service-role only. Never SELECT this into application output or a migration result.';

-- Accessor used by the cron command so the command carries no literal.
-- SECURITY DEFINER so pg_cron (running as the job owner) can read it while the
-- table itself stays unreadable to every other role.
create or replace function private.cron_secret(p_name text)
returns text
language sql
stable
security definer
set search_path to 'private'
as $$
  select secret from private.cron_secrets where name = p_name;
$$;

revoke all on function private.cron_secret(text) from public, anon, authenticated;

-- Generate the secret IN the database. 32 random bytes, hex encoded.
-- `on conflict do nothing` so re-running this migration never silently rotates
-- the secret out from under a running cron job.
insert into private.cron_secrets (name, secret)
values ('lead_followup', encode(gen_random_bytes(32), 'hex'))
on conflict (name) do nothing;
